version: 2.1

jobs:
  build:
    docker:
      - image: circleci/dotnet:3.1
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --configuration Release
      - run:
          name: Run Tests
          command: dotnet test

workflows:
  version: 2
  build:
    jobs:
      - build
